import { SvgIcon } from "src/types/icons/SvgIcon";

export const AddElementIcon: SvgIcon
export const AirTableIcon: SvgIcon
export const ArrowDownIcon: SvgIcon
export const ArrowUpIcon: SvgIcon
export const BackArrowIcon: SvgIcon
export const BagIcon: SvgIcon
export const BarChartIcon: SvgIcon
export const BasketIcon: SvgIcon
export const BeakerIcon: SvgIcon
export const BellIcon: SvgIcon
export const BillIcon: SvgIcon
export const BlockIcon: SvgIcon
export const BluetoothIcon: SvgIcon
export const BookIcon: SvgIcon
export const BoxIcon: SvgIcon
export const BugIcon: SvgIcon
export const CalculatorIcon: SvgIcon
export const CalendarClockIcon: SvgIcon
export const CardCashIcon: SvgIcon
export const CartIcon: SvgIcon
export const CashBoxIcon: SvgIcon
export const CashIcon: SvgIcon
export const CashDrawerIcon: SvgIcon
export const CashTransferIcon: SvgIcon
export const ChatIcon: SvgIcon
export const CheckIcon: SvgIcon
export const CircleIcon: SvgIcon
export const CircleCheckIcon: SvgIcon
export const CircleCrossIcon: SvgIcon
export const ClipboardCheckIcon: SvgIcon
export const ClipboardIcon: SvgIcon
export const ClipboardsIcon: SvgIcon
export const ClockIcon: SvgIcon
export const ClosedEyeIcon: SvgIcon
export const CommandIcon: SvgIcon
export const CookingPotIcon: SvgIcon
export const CopyIcon: SvgIcon
export const CreditCardIcon: SvgIcon
export const CrossIcon: SvgIcon
export const CutleryIcon: SvgIcon
export const DepositIcon: SvgIcon
export const DeviceIcon: SvgIcon
export const DishIcon: SvgIcon
export const IncomingIcon: SvgIcon
export const CashRegisterShiftIcon: SvgIcon
export const DocumentIcon: SvgIcon
export const DoorbellIcon: SvgIcon
export const DoorHangerIcon: SvgIcon
export const DownloadIcon: SvgIcon
export const DragIcon: SvgIcon
export const EditIcon: SvgIcon
export const EnvelopeIcon: SvgIcon
export const ExchangeArrowsIcon: SvgIcon
export const EyeIcon: SvgIcon
export const FilledChartDonutIcon: SvgIcon
export const FilledCircleIcon: SvgIcon
export const FilledClockIcon: SvgIcon
export const FilledCustomerIcon: SvgIcon
export const FilterIcon: SvgIcon
export const FlappyDiskIcon: SvgIcon
export const FoldersIcon: SvgIcon
export const FoodBagIcon: SvgIcon
export const GearIcon: SvgIcon
export const GramsIcon: SvgIcon
export const GridIcon: SvgIcon
export const HistoryIcon: SvgIcon
export const HomeIcon: SvgIcon
export const IdentifierIcon: SvgIcon
export const InfoIcon: SvgIcon
export const InvoiceIcon: SvgIcon
export const KilogramsIcon: SvgIcon
export const LightBulbIcon: SvgIcon
export const LightingIcon: SvgIcon
export const LinkIcon: SvgIcon
export const ListIcon: SvgIcon
export const LitreIcon: SvgIcon
export const MinimalistMotorcycleIcon: SvgIcon
export const FoodBoxIcon: SvgIcon
export const RestoreIcon: SvgIcon
export const LockIcon: SvgIcon
export const MapIcon: SvgIcon
export const MapPinIcon: SvgIcon
export const MegaphoneIcon: SvgIcon
export const MilliliterIcon: SvgIcon
export const MobileIcon: SvgIcon
export const MoneyBagIcon: SvgIcon
export const MoneyIcon: SvgIcon
export const MotorcycleIcon: SvgIcon
export const NoPhotoIcon: SvgIcon
export const NoteIcon: SvgIcon
export const OpenBoxIcon: SvgIcon
export const OutlinedLightBulbIcon: SvgIcon
export const OutlinedPeopleIcon: SvgIcon
export const OutlinedPlusIcon: SvgIcon
export const PaymentTerminalIcon: SvgIcon
export const PdfIcon: SvgIcon
export const PennantIcon: SvgIcon
export const PeopleIcon: SvgIcon
export const PhoneIcon: SvgIcon
export const PideDirectoIcon: SvgIcon
export const PieChartIcon: SvgIcon
export const PinIcon: SvgIcon
export const PrinterIcon: SvgIcon
export const PlusIcon: SvgIcon
export const QuestionIcon: SvgIcon
export const ReceiptIcon: SvgIcon
export const RefreshIcon: SvgIcon
export const RouteIcon: SvgIcon
export const SaveIcon: SvgIcon
export const ScissorsIcon: SvgIcon
export const SearchIcon: SvgIcon
export const SettingsIcon: SvgIcon
export const SpeakerIcon: SvgIcon
export const SpeakerOffIcon: SvgIcon
export const StarIcon: SvgIcon
export const StoreIcon: SvgIcon
export const SurveyIcon: SvgIcon
export const TableIcon: SvgIcon
export const TicketIcon: SvgIcon
export const TicketsIcon: SvgIcon
export const TransactionIcon: SvgIcon
export const TrendingDownIcon: SvgIcon
export const TrendingUpIcon: SvgIcon
export const TrashCanIcon: SvgIcon
export const UnLockIcon: SvgIcon
export const UploadIcon: SvgIcon
export const UsbIcon: SvgIcon
export const UserIcon: SvgIcon
export const UsersIcon: SvgIcon
export const VideoIcon: SvgIcon
export const WarningIcon: SvgIcon
export const WifiIcon: SvgIcon
export const WithdrawIcon: SvgIcon
export const XmlFileIcon: SvgIcon
